Repository wdt-dev/couchbase-liquibase, pull requests merged in 2023-06, with the labels that each got.

#15 COS-267 Fix pipeline fail on whereCondition tests
  liquibase-couchbase/src/test/java/integration/statement/RemoveDocumentsQueryStatementIT.java
Labels: bug, PR: Review Needed

#14 COS-191: improve statement test coverage
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/changelog/CouchbaseChangeLog.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/mapper/ChangeSetMapper.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/serializer/LocalDateTimeDeserializer.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/serializer/LocalDateTimeSerializer.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/mapper/ChangeSetMapperTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/BucketExistsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CollectionExistsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CouchbaseSqlStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CreateBucketStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CreatePrimaryQueryIndexStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CreateQueryIndexStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/CreateScopeStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DocumentExistsByKeyStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DropBucketStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DropCollectionStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DropIndexStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DropPrimaryIndexStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/DropScopeStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/ExecuteQueryStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/InsertDocumentsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/InsertFileContentStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/MutateInQueryStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/MutateInStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/RemoveDocumentsQueryStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/RemoveDocumentsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/ScopeExistsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/UpdateBucketStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/UpsertDocumentsStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/UpsertFileContentStatementTest.java
Labels: PR: Review Needed

#8 COS-262 system tests for maven
  test-project/pom.xml
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/common/ContainerizedTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/common/TestContainerInitializer.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/containers/JavaMavenContainer.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/test/CreateBucketSystemTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/test/CreateCollectionSystemTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/test/CreateScopeSystemTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/test/InsertDocumentsSystemTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/test/UpsertDocumentsSystemTest.java
  test-project/src/test/java/org/liquibase/ext/couchbase/plugin/util/TestPropertyProvider.java
  test-project/src/test/resources/Dockerfile
  test-project/src/test/resources/build-dependency.sh
  test-project/src/test/resources/changelogs/create-bucket.xml
  test-project/src/test/resources/changelogs/create-collection.xml
  test-project/src/test/resources/changelogs/create-scope.xml
  test-project/src/test/resources/changelogs/custom-settings-mock-test.xml
  test-project/src/test/resources/changelogs/insert-documents.xml
  test-project/src/test/resources/changelogs/upsert-documents.xml
  test-project/src/test/resources/liquibase-update-command.sh
  test-project/src/test/resources/liquibase.properties
  test-project/src/test/resources/mvntest/liquibase-couchbase.properties
  test-project/src/test/resources/test.properties
Labels: PR: Review Needed

#18 COS-191: test coverage for provider package
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/ContextServiceProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/ExpressionDocumentKeyProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/IncrementalDocumentKeyProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/UidDocumentKeyProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/generator/IncrementalKeyGenerator.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/mapper/ChangeSetMapperTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/mapper/LinesMapperTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/ContextServiceProviderTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/ExpressionDocumentKeyProviderTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/FieldDocumentKeyProviderTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/IncrementalDocumentKeyProviderTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/UidDocumentKeyProviderTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/factory/DocumentKeyProviderFactoryTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/generator/IncrementalKeyGeneratorTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/generator/UidKeyGeneratorTest.java
Labels: PR: Review Needed, PR: FixIt

#27 COS-191: Lockservice test coverage
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/configuration/CouchbaseLiquibaseConfiguration.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/lockservice/CouchbaseLockService.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/lockservice/CouchbaseChangelogLockerTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/lockservice/CouchbaseLockServiceTest.java
  spring-boot-starter-liquibase-couchbase-test/src/test/java/org/liquibase/ext/couchbase/starter/test/CustomSettingsSystemTest.java
Labels: PR: Review Needed

#28 COS-273. unit tests for changelog package
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/changelog/CouchbaseHistoryService.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/changelog/NoSqlHistoryService.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/changelog/CouchbaseHistoryServiceTest.java
Labels: PR: Good to Merge

#25 COS-271 Added sql++ query field in 'mutateIn' change
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/MutateInChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/operator/ClusterOperator.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/MutateInSqlQueryStatement.java
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.json
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.xsd
  liquibase-couchbase/src/test/java/common/constants/ChangeLogSampleFilePaths.java
  liquibase-couchbase/src/test/java/integration/statement/MutateInSqlQueryStatementIT.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/MutateInChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/MutateInSqlQueryStatementTest.java
  liquibase-couchbase/src/test/java/system/change/MutateInQuerySystemTest.java
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/mutatein/changelog.mutate-in-insert.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/mutatein/changelog.mutate-in-replace-document-sql++-filter.test.xml
Labels: PR: FixIt

#4 [Snyk] Upgrade com.couchbase.client:java-client from 3.4.3 to 3.4.6
  liquibase-couchbase/pom.xml
Labels: PR: Review Needed

#20 [Snyk] Upgrade org.springframework.boot:spring-boot-starter from 2.7.9 to 2.7.11
  spring-boot-starter-liquibase-couchbase-test/pom.xml
Labels: PR: Review Needed

#21 [Snyk] Upgrade io.projectreactor:reactor-core from 3.5.5 to 3.5.6
  spring-boot-starter-liquibase-couchbase-test/pom.xml
Labels: PR: Review Needed

#29 Fix dependencies versions (Snyk check fix) and checksums
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/lockservice/CouchbaseLockService.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/CreateCollectionChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/CreatePrimaryQueryIndexChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/CreateQueryIndexChangeTest.java
  pom.xml
Labels: PR: Good to Merge

#30 COS-191: add tests on remaining classes
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/database/CouchbaseConnection.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/database/CouchbaseLiquibaseDatabase.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/PropertyProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/BucketScope.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/Field.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/File.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/Keyspace.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/MutateInChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/RemoveDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/database/CouchbaseConnectionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/database/CouchbaseLiquibaseDatabaseTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/executor/CouchbaseExecutorTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/CollectionExistsPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/BucketScopeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/DocumentTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/FieldTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/FileTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/KeyspaceTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/ParamTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/ValueTest.java
Labels: PR: Review Needed

#34 COS-281. Removed guava library and added apache commons to jar
  liquibase-couchbase/pom.xml
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/operator/ChangeLogOperator.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/ExpressionDocumentKeyProvider.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/reader/SqlFileReader.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/CouchbaseFileContentStatement.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/validator/JsonChangelogValidator.java
  liquibase-couchbase/src/test/java/integration/statement/InsertDocumentsStatementIT.java
  liquibase-couchbase/src/test/java/integration/statement/RemoveDocumentsQueryStatementIT.java
  liquibase-couchbase/src/test/java/integration/statement/RemoveDocumentsStatementIT.java
  liquibase-couchbase/src/test/java/integration/statement/UpsertDocumentsStatementIT.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/CreateQueryIndexChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/ExecuteQueryChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/InsertDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/RemoveDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/UpsertDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/operator/ClusterOperatorTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/operator/CollectionOperatorTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/CollectionExistsPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/DocumentExistsByKeyPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/IndexExistsPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/PrimaryIndexExistsPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/ScopeExistsPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/SqlCheckCountPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/SqlCheckPreconditionTest.java
  liquibase-couchbase/src/test/java/system/change/RemoveDocumentsSystemTest.java
Labels: PR: Review Needed

#26 COS-265 Added sql++ query field in 'RemoveDocuments' change
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/RemoveDocumentsChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/operator/ClusterOperator.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/operator/CollectionOperator.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/RemoveDocumentsSqlQueryStatement.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/RemoveDocumentsStatement.java
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.json
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.xsd
  liquibase-couchbase/src/test/java/common/constants/ChangeLogSampleFilePaths.java
  liquibase-couchbase/src/test/java/integration/statement/RemoveDocumentsSqlQueryStatementIT.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/MutateInSqlQueryStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/RemoveDocumentsSqlQueryStatementTest.java
  liquibase-couchbase/src/test/java/system/change/RemoveDocumentsSystemTest.java
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/remove/changelog.remove-documents-sql++.test.xml
Labels: PR: Good to Merge, PR: Conflicts

#35 COS-189: refactor file tags
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/DocumentsChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/InsertDocumentsChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/SqlFileChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/UpsertDocumentsChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/mapper/DocFileMapper.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/mapper/LinesMapper.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/mapper/ListMapper.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/provider/factory/DocumentKeyProviderFactory.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/CouchbaseFileContentStatement.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/InsertFileContentStatement.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/statement/UpsertFileContentStatement.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/File.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/types/ImportFile.java
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.xsd
  liquibase-couchbase/src/test/java/integration/statement/RemoveDocumentsSqlQueryStatementIT.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/InsertDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/InsertFromFileChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/SqlFileChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/UpsertDocumentsChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/UpsertFromFileChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/mapper/LinesMapperTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/provider/factory/DocumentKeyProviderFactoryTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/InsertFileContentStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/statement/UpsertFileContentStatementTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/FileTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/types/ImportFileTest.java
  liquibase-couchbase/src/test/java/system/change/CreateQueryIndexSystemTest.java
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/collection/changelog.create-collection-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-document-rollback-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-document-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-from-file-expression-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-from-file-increment-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-from-file-uid-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-from-file.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.upsert-from-file-expression-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.upsert-from-file-increment-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.upsert-from-file-uid-key.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.upsert-from-file.test.xml
  test-project/src/main/resources/liquibase/changetypes/insert-documents.xml
  test-project/src/main/resources/liquibase/changetypes/sql-file.xml
  test-project/src/main/resources/liquibase/changetypes/upsert-documents.xml
Labels: PR: Review Needed

#36 COS-212. Rename couchbase query xsd components
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/change/QueryFileChange.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/exception/precondition/SqlCheckCountPreconditionException.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/exception/precondition/SqlCheckPreconditionException.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/precondition/QueryCountCheckPrecondition.java
  liquibase-couchbase/src/main/java/liquibase/ext/couchbase/precondition/QueryCustomCheckPrecondition.java
  liquibase-couchbase/src/main/resources/META-INF/services/liquibase.change.Change
  liquibase-couchbase/src/main/resources/META-INF/services/liquibase.precondition.Precondition
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.json
  liquibase-couchbase/src/main/resources/www.liquibase.org/xml/ns/dbchangelog/dbchangelog-couchbase-ext.xsd
  liquibase-couchbase/src/test/java/integration/precondition/QueryCountCheckPreconditionIT.java
  liquibase-couchbase/src/test/java/integration/precondition/QueryCustomCheckPreconditionIT.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/change/QueryFileChangeTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/QueryCountCheckPreconditionTest.java
  liquibase-couchbase/src/test/java/liquibase/ext/couchbase/precondition/QueryCustomCheckPreconditionTest.java
  liquibase-couchbase/src/test/java/system/precondition/QueryCustomCheckPreconditionSystemTest.java
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/bucket/changelog.execute-query.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/collection/changelog.create-collection-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-document-rollback-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/insert/changelog.insert-document-sql.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/precondition/changelog.sql-check-precondition-failed.test.xml
  liquibase-couchbase/src/test/resources/liquibase/ext/couchbase/precondition/changelog.sql-check-precondition.test.xml
  test-project/src/main/resources/liquibase/changetypes/sql-file.xml
  test-project/src/main/resources/liquibase/preconditions/sql-check-precondition.xml
Labels: PR: Good to Merge
